import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import numpy as np

# cvs
data_1 = pd.read_csv('../project_dataset/extract - cash request - data analyst.csv')
data_2 = pd.read_csv('../project_dataset/extract - fees - data analyst - .csv')

st.title("Cohort Analysis for Ironhack Payments 💰")

st.header("DataFrame for Cash Request:")
st.dataframe(data_1.head(10))

st.header("DataFrame for Fees:")
st.dataframe(data_2.head(10))

# Sample DataFrame
data = {
    'count': [289, 223, 184, 244, 473, 837, 2615, 3601, 3417, 4221, 7725, 140],
}
months = ['2019-12', '2020-01', '2020-02', '2020-03', '2020-04', '2020-05', '2020-06', '2020-07', '2020-08', '2020-09', '2020-10', '2020-11']

# Create a DataFrame with 'month_created' as index
df = pd.DataFrame(data, index=pd.to_datetime(months))

# Display DataFrame in Streamlit
st.header("Monthly Count Histogram")

# Plotting the histogram (bar plot) using Plotly for interactivity
fig = px.bar(df, x=df.index, y='count', labels={'count': 'Count', 'index': 'Month'}, title='Monthly Count Histogram')

# Show the plot in Streamlit
st.plotly_chart(fig)

st.markdown("<h2 style='text-align: center; color: black;'>Select an Analysis</h2>", unsafe_allow_html=True)

# Custom Radio Button Styling
option_selected = st.radio(
    "Choose one of the following options:",
    ['Frequency of Service Usage', 'Incident Rate', 'Revenue Generated by the Cohort', 'Fee Types Usage'],
    index=0
)

# Display different content based on the selected option
if option_selected == 'Frequency of Service Usage':
    data = {
        'absolute_frequency': [21719, 2251],
        'relative_frequency': [0.91, 0.09]
    }

    # Create DataFrame with 'cohort' as the index
    df_freq = pd.DataFrame(data, index=['Cohort-2', 'Cohort-1'])

    # Reset the index to move 'cohort' from index to a column
    df_freq.reset_index(inplace=True)

    # Rename columns to match expected names
    df_freq.columns = ['cohort', 'absolute_frequency', 'relative_frequency']

    # Define the desired order of cohorts (if necessary)
    desired_order = ['Cohort-1', 'Cohort-2']  # Adjust based on your cohort names
    df_freq = df_freq.set_index('cohort')  # Set 'cohort' as the index again (optional)

    # Reorder the DataFrame according to the desired order
    df_freq = df_freq.loc[desired_order]

    #  Streamlit Title
    st.header('Cohort Analysis - Absolute and Relative Frequency')

    # Plot the data with two y-axes
    fig, ax1 = plt.subplots()

    # Plot the absolute frequency on the left y-axis
    ax1.bar(df_freq.index, df_freq['absolute_frequency'], color='b', alpha=0.6, label='Absolute Frequency')
    ax1.set_xlabel('Cohorts')
    ax1.set_ylabel('Absolute Frequency', color='b')
    ax1.tick_params(axis='y', labelcolor='b')

    # Create a second y-axis for the relative frequency
    ax2 = ax1.twinx()
    ax2.plot(df_freq.index, df_freq['relative_frequency'], color='r', label='Relative Frequency', marker='o')
    ax2.set_ylabel('Relative Frequency', color='r')
    ax2.tick_params(axis='y', labelcolor='r')

    # Add title and show the plot
    fig.tight_layout()

    # Display the plot in Streamlit
    st.pyplot(fig)

elif option_selected == 'Incident Rate':
    st.subheader('Number of Incident by Cohort')
    # Example data (replace with your actual data)
    data = {
        'cohort': ['Cohort-1', 'Cohort-2'],
        'False': [1957, 18683],
        'True': [294, 3036]
    }   

    # Convert to DataFrame
    df = pd.DataFrame(data)

    # Create a new DataFrame with 'cohort' and 'True' values (for interactive plot)
    df_true = df[['cohort', 'True']]

    # Plotting the interactive bar plot using Plotly
    fig = px.bar(df_true, x='cohort', y='True', labels={'True': 'Number of Incidents', 'cohort': 'Cohort'},
             title='Number of Incidents by Cohort')

    # Show the interactive plot in Streamlit
    st.plotly_chart(fig)

    st.subheader('Proportion of Incident by Cohort')
    # Example data (replace with your actual data)
    
    data = {
        'cohort': ['Cohort-1', 'Cohort-2'],
        'False': [0.87, 0.86],
        'True': [0.13, 0.14]
    }   

    # Convert to DataFrame
    df = pd.DataFrame(data)

    # Create a new DataFrame with 'cohort' and 'True' values (for interactive plot)
    df_true = df[['cohort', 'True']]

    # Plotting the interactive bar plot using Plotly
    fig = px.bar(df_true, x='cohort', y='True', labels={'True': 'Proportion of incidents', 'cohort': 'Cohort'},
             title='Number of Incidents by Cohort',
             color_discrete_map={'Cohort-1': 'red', 'Cohort-2': 'blue'})

    # Show the interactive plot in Streamlit
    st.plotly_chart(fig)

elif option_selected == 'Revenue Generated by the Cohort':
    # Example total amounts for the cohorts
    cohort1_total = 1290
    cohort2_total = 104000

    # Data preparation
    data = {
        "cohort": ["Cohort-1", "Cohort-2"],
        "Total_amount": [cohort1_total, cohort2_total]
    }

    # Create DataFrame
    df = pd.DataFrame(data)

    # Plotting the interactive bar plot using Plotly
    fig = px.bar(df, x='cohort', y='Total_amount', 
             labels={'Total_amount': 'Revenue', 'cohort': 'Cohort'},
             title='Total Revenue by Cohort',
             color='cohort',  # Color bars by cohort for automatic color assignment
             color_discrete_map={'Cohort-1': 'red', 'Cohort-2': 'blue'})  # Custom colors

    # Remove the legend by setting showlegend to False
    fig.update_layout(showlegend=False)
    
    # Show the interactive plot in Streamlit
    st.plotly_chart(fig)

elif option_selected == 'Fee Types Usage':
    proportions_fees = {
        'cohort': ['Cohort-1', 'Cohort-2'],
        'incident': [0.17, 0.1],
        'instant_payment': [0, 0.53],
        'postpone': [0.83, 0.36]
    }

    # Convert dictionary to pandas DataFrame
    df_proportions = pd.DataFrame(proportions_fees)

    # Reshape the DataFrame into long format using `pd.melt`
    df_long = pd.melt(df_proportions, id_vars=['cohort'], value_vars=['incident', 'instant_payment', 'postpone'], 
                  var_name='fee_type', value_name='proportion')

    # Create the Plotly bar chart with the reshaped DataFrame
    fig = px.bar(df_long, 
                x='cohort', 
                y='proportion', 
                color='fee_type',  # Color by fee type
                labels={'proportion': 'Proportion', 'cohort': 'Cohort', 'fee_type': 'Fee Type'},
                title='Proportions of Fee Types by Cohort',
                color_discrete_map={'incident': 'blue', 'instant_payment': 'red', 'postpone': 'forestgreen'}  # Custom colors
                )
    # Remove the legend by setting showlegend to False
    fig.update_layout(showlegend=False)

    # Show the interactive plot in Streamlit
    st.plotly_chart(fig)